name: bulkSeq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - _sysroot_linux-64_curr_repodata_hack=3
  - attrs=22.1.0
  - bbmap=38.84
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35.1
  - biopython=1.78
  - blas=1.0
  - bottleneck=1.3.5
  - bowtie2=2.3.5.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bwidget=1.9.16
  - bz2file=0.98
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cairo=1.14.12
  - certifi=2022.12.7
  - curl=7.87.0
  - cutadapt=4.4
  - cycler=0.11.0
  - dbus=1.13.18
  - dnaio=0.10.0
  - expat=2.6.3
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - fuzzysearch=0.7.3
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.63.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=1.8.8
  - htseq=2.0.3
  - htslib=1.13
  - icu=58.2
  - idr=2.0.4.2
  - intel-openmp=2021.4.0
  - isa-l=2.30.0
  - joblib=1.1.1
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20210714
  - libev=4.33
  - libffi=3.2.1
  - libgcc=14.2.0
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=14.2.0
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - macs2=2.2.6
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.0.7
  - ncurses=6.2
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openjdk=8.0.152
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.3.5
  - pango=1.42.4
  - pbzip2=1.1.13
  - pcre=8.45
  - perl=5.34.0
  - picard=3.0.0
  - pigz=2.6
  - pillow=8.3.1
  - pip=22.3.1
  - pixman=0.40.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysam=0.15.4
  - python=3.7.7
  - python-dateutil=2.8.2
  - python-isal=1.1.0
  - python_abi=3.7
  - pytz=2022.7
  - qt=5.9.7
  - r-base=3.4.3
  - readline=7.0
  - regex=2022.7.9
  - samtools=1.13
  - scipy=1.7.3
  - setuptools=65.6.3
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.33.0
  - sysroot_linux-64=2.17
  - tbb=2020.3
  - tk=8.6.14
  - tktable=2.10
  - tornado=6.2
  - typing_extensions=4.4.0
  - umi_tools=1.0.1
  - wheel=0.38.4
  - xopen=1.6.0
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.5
